export * from './imagens/wellCome/Balance.png'
export * from './imagens/wellCome/Calories.png'
export * from './imagens/wellCome/Nutrients.png'
export * from './imagens/onBoard/Man'
export * from './imagens/onBoard/Woman'
export * from './imagens/onBoard/Fruit'
export * from './imagens/onBoard/Hamburger'
export * from './imagens/onBoard/Heart'
